---
- name: install default Apache Web Server
  hosts: all
  become: yes

  tasks:
  - name: install Apache Webserver
    apt: name=apache2 state=latest
    register: command_output
    
  - name: Start Apache and Enable it on the every boot
    service: name=apache2 state=started enabled=yes
    register: command_output
 
  - debug: var=command_output.stdout_lines
